name: Revalidate Company Website

on:
  push:
    paths:
      - src/pages/blog/*.md
      - src/pages/blog/*.mdx
    branches:
      - main
      - michaelkhakhel-web-144-rebuild-the-app-after-files-changed-in

jobs:
  revalidate:
    name: Revalidate Company Website blogs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Get modified files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: src/pages/blog/*.{md,mdx}

      - name: Get file names (slugs) and send it to revalidate API
        run: |
          ALL_CHANGED_FILES="${{steps.changed-files.outputs.all_changed_files}}"
          IFS=' ' read -r -a file_array <<< "$ALL_CHANGED_FILES"

          file_names=""
          for file in "${file_array[@]}"; do
            file_name="$(echo "$file" | awk -F/ '{print $NF}' | awk -F. '{print $1}')"
            file_names="$file_names\"$file_name\","
          done
          file_names="[${file_names%,}]"
          FILE_NAMES_JSON=$(echo "$file_names" | jq -c '.')
          API_BODY="{\"documents\":$FILE_NAMES_JSON, \"type\":\"api-update\", \"secret\": ${{ secrets.GH_REVALIDATION_SECRET}"
          echo "GH_REVALIDATION_URL is: ${{ secrets.GH_REVALIDATION_URL }}"
          curl -X POST -d "$API_BODY" ${{ secrets.GH_REVALIDATION_URL }} -H "Content-Type: application/json"
